version: '3.5'

services:
    texera:
        build:
            context: ../..
            dockerfile: ./Dockerfile
        hostname: texera
        expose:
            - "8080"

    nginx-server:
        image: nginx:alpine-slim
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - texera
        ports:
            - "9870:9870"

    db:
        image: mysql:8
        hostname: texera-db
        volumes:
            # - ./mysql:/var/lib/mysql
            - ../scripts/sql/texera_ddl.sql:/docker-entrypoint-initdb.d/00_texera_ddl.sql
            - ./user_init.sql:/docker-entrypoint-initdb.d/01_user_init.sql
        environment:
            MYSQL_ROOT_PASSWORD: pass
        expose:
            - "3306"
